version: '2'
services:
  smartwords-server:
    image: node:8
    volumes:
      - .:/smartwords-server
    working_dir: /smartwords-server
    #command: bash -c "npm i --registry=https://registry.npm.taobao.org && npm run build && npm start"
    command: bash -c "npm i --registry=https://registry.npm.taobao.org && npm run dev"
    ports:
      - "3000:3000"
