version: '2'
services:
  mini-force-service:
    image: registry.cn-hangzhou.aliyuncs.com/jeffhtli/docker-node-puppeteer
    volumes:
      - .:/mini-force
    working_dir: /mini-force
    command: bash -c "npm i --registry=https://registry.npm.taobao.org && npm run build && npm start"
    #command: bash -c "npm i --registry=https://registry.npm.taobao.org && node server.js"
    ports:
      - "3002:3000"
